### ISSUE TITLE
Cuda Error when generating 3D models with textures

### ISSUE THREAD

**Issue by CoolJayWee** [nv-tlabs/GET3D#59] opened 2022-11-14 05:23 UTC
Hello,

I am having this error below. Please help.

`(base) get3dadm@nubgpu02:~$ python train_3d.py --outdir=save_inference_results/s                                                                   hapenet_car  --gpus=1 --batch=4 --gamma=40 --data_camera_mode shapenet_car  --dm                                                                   tet_scale 1.0  --use_shapenet_split 1  --one_3d_generator 1  --fp32 0 --inferenc                                                                   e_vis 1 --resume_pretrain shapenet_car.pt --inference_to_generate_textured_mesh                                                                    1
python: can't open file '/home/get3dadm/train_3d.py': [Errno 2] No such file or                                                                    directory
(base) get3dadm@nubgpu02:~$ dir
anaconda3  Anaconda3-2022.10-Linux-x86_64.sh  GET3D
(base) get3dadm@nubgpu02:~$ cd GET3D/
(base) get3dadm@nubgpu02:~/GET3D$ python train_3d.py --outdir=save_inference_res                                                                   ults/shapenet_car  --gpus=1 --batch=4 --gamma=40 --data_camera_mode shapenet_car                                                                     --dmtet_scale 1.0  --use_shapenet_split 1  --one_3d_generator 1  --fp32 0 --in                                                                   ference_vis 1 --resume_pretrain shapenet_car.pt --inference_to_generate_textured                                                                   _mesh 1
==> start
==> use shapenet dataset
==> ERROR!!!! THIS SHOULD ONLY HAPPEN WHEN USING INFERENCE
==> use image path: ./tmp, num images: 1234
==> launch training

Training options:
{
  "G_kwargs": {
    "class_name": "training.networks_get3d.GeneratorDMTETMesh",
    "z_dim": 512,
    "w_dim": 512,
    "mapping_kwargs": {
      "num_layers": 8
    },
    "one_3d_generator": true,
    "n_implicit_layer": 1,
    "deformation_multiplier": 1.0,
    "use_style_mixing": true,
    "dmtet_scale": 1.0,
    "feat_channel": 16,
    "mlp_latent_channel": 32,
    "tri_plane_resolution": 256,
    "n_views": 1,
    "render_type": "neural_render",
    "use_tri_plane": true,
    "tet_res": 90,
    "geometry_type": "conv3d",
    "data_camera_mode": "shapenet_car",
    "channel_base": 32768,
    "channel_max": 512,
    "fused_modconv_default": "inference_only"
  },
  "D_kwargs": {
    "class_name": "training.networks_get3d.Discriminator",
    "block_kwargs": {
      "freeze_layers": 0
    },
    "mapping_kwargs": {},
    "epilogue_kwargs": {
      "mbstd_group_size": 4
    },
    "data_camera_mode": "shapenet_car",
    "add_camera_cond": true,
    "channel_base": 32768,
    "channel_max": 512,
    "architecture": "skip"
  },
  "G_opt_kwargs": {
    "class_name": "torch.optim.Adam",
    "betas": [
      0,
      0.99
    ],
    "eps": 1e-08,
    "lr": 0.002
  },
  "D_opt_kwargs": {
    "class_name": "torch.optim.Adam",
    "betas": [
      0,
      0.99
    ],
    "eps": 1e-08,
    "lr": 0.002
  },
  "loss_kwargs": {
    "class_name": "training.loss.StyleGAN2Loss",
    "gamma_mask": 40.0,
    "r1_gamma": 40.0,
    "style_mixing_prob": 0.9,
    "pl_weight": 0.0
  },
  "data_loader_kwargs": {
    "pin_memory": true,
    "prefetch_factor": 2,
    "num_workers": 3
  },
  "inference_vis": true,
  "inference_to_generate_textured_mesh": true,
  "inference_save_interpolation": false,
  "inference_compute_fid": false,
  "inference_generate_geo": false,
  "training_set_kwargs": {
    "class_name": "training.dataset.ImageFolderDataset",
    "path": "./tmp",
    "use_labels": false,
    "max_size": 1234,
    "xflip": false,
    "resolution": 1024,
    "data_camera_mode": "shapenet_car",
    "add_camera_cond": true,
    "camera_path": "./tmp",
    "split": "test",
    "random_seed": 0
  },
  "resume_pretrain": "shapenet_car.pt",
  "D_reg_interval": 16,
  "num_gpus": 1,
  "batch_size": 4,
  "batch_gpu": 4,
  "metrics": [
    "fid50k"
  ],
  "total_kimg": 20000,
  "kimg_per_tick": 1,
  "image_snapshot_ticks": 50,
  "network_snapshot_ticks": 200,
  "random_seed": 0,
  "ema_kimg": 1.25,
  "G_reg_interval": 4,
  "run_dir": "save_inference_results/shapenet_car/inference"
}

Output directory:    save_inference_results/shapenet_car/inference
Number of GPUs:      1
Batch size:          4 images
Training duration:   20000 kimg
Dataset path:        ./tmp
Dataset size:        1234 images
Dataset resolution:  1024
Dataset labels:      False
Dataset x-flips:     False

Creating output directory...
Launching processes...
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "filtered_lrelu_plugin"... Done.
==> resume from pretrained path shapenet_car.pt
==> generate
/home/get3dadm/GET3D/training/networks_get3d.py:430: UserWarning: torch.range is                                                                    deprecated and will be removed in a future release because its behavior is inco                                                                   nsistent with Python's range builtin. Instead, use torch.arange, which produces                                                                    values in [start, end).
  camera_theta = torch.range(0, n_camera - 1, device=self.device).unsqueeze(dim=                                                                   -1) / n_camera * math.pi * 2.0
Traceback (most recent call last):
  File "/home/get3dadm/GET3D/train_3d.py", line 330, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/home/get3dadm/anaconda3/lib/python3.9/site-packages/click/core.py", lin                                                                   e 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/get3dadm/anaconda3/lib/python3.9/site-packages/click/core.py", lin                                                                   e 1053, in main
    rv = self.invoke(ctx)
  File "/home/get3dadm/anaconda3/lib/python3.9/site-packages/click/core.py", lin                                                                   e 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/get3dadm/anaconda3/lib/python3.9/site-packages/click/core.py", lin                                                                   e 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/get3dadm/GET3D/train_3d.py", line 324, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "/home/get3dadm/GET3D/train_3d.py", line 103, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "/home/get3dadm/GET3D/train_3d.py", line 46, in subprocess_fn
    inference_3d.inference(rank=rank, **c)
  File "/home/get3dadm/GET3D/training/inference_3d.py", line 87, in inference
    save_visualization(
  File "/home/get3dadm/GET3D/training/inference_utils.py", line 182, in save_vis                                                                   ualization
    img, mask, sdf, deformation, v_deformed, mesh_v, mesh_f, gen_camera, img_wo_                                                                   light, tex_hard_mask = G_ema.generate_3d(
  File "/home/get3dadm/GET3D/training/networks_get3d.py", line 678, in generate_                                                                   3d
    sdf_reg_loss, render_return_value = self.synthesis.generate(
  File "/home/get3dadm/GET3D/training/networks_get3d.py", line 479, in generate
    antilias_mask, hard_mask, return_value = self.render_mesh(mesh_v, mesh_f, ca                                                                   m_mv)
  File "/home/get3dadm/GET3D/training/networks_get3d.py", line 337, in render_me                                                                   sh
    return_value = self.dmtet_geometry.render_mesh(
  File "/home/get3dadm/GET3D/uni_rep/rep_3d/dmtet.py", line 462, in render_mesh
    tex_pos, mask, hard_mask, rast, v_pos_clip, mask_pyramid, depth = self.rende                                                                   rer.render_mesh(
  File "/home/get3dadm/GET3D/uni_rep/render/neural_render.py", line 74, in rende                                                                   r_mesh
    rast, db = peeler.rasterize_next_layer()
  File "/home/get3dadm/anaconda3/lib/python3.9/site-packages/nvdiffrast/torch/op                                                                   s.py", line 378, in rasterize_next_layer
    result = _rasterize_func.apply(self.raster_ctx, self.pos, self.tri, self.res                                                                   olution, self.ranges, self.grad_db, self.peeling_idx)
  File "/home/get3dadm/anaconda3/lib/python3.9/site-packages/nvdiffrast/torch/op                                                                   s.py", line 246, in forward
    out, out_db = _get_plugin(gl=True).rasterize_fwd_gl(raster_ctx.cpp_wrapper,                                                                    pos, tri, resolution, ranges, peeling_idx)
RuntimeError: Cuda error: 1[cudaGraphicsGLRegisterImage(&s.cudaColorBuffer[i], s                                                                   .glColorBuffer[i], GL_TEXTURE_3D, cudaGraphicsRegisterFlagsReadOnly);]
`

**Comment by SteveJunGao** [comment] 2022-11-20 19:35
Hi @CoolJayWee ,

It seems the problem is related to OpenGL. Can you the fix mentioned in this issue #61 ? 

If you change the [this line](https://github.com/nv-tlabs/GET3D/blob/master/uni_rep/render/neural_render.py#L59) from `self.ctx = dr.RasterizeGLContext(device=self.device)` to `self.ctx = dr.RasterizeCudaContext(device=self.device)` This will change from OpenGL to Cuda and won't require installing OpenGL.

**Comment by SteveJunGao** [comment] 2023-01-12 21:13
Close this issue as no update received

**Closed by SteveJunGao** 2023-01-12 21:13 UTC
